import pytest
import io
from pypdf import PdfWriter
from app.core.ingestion.pdf_parser import extract_text_from_pdf

def create_sample_pdf(text_content):
    writer = PdfWriter()
    page = writer.add_blank_page(width=72, height=72)
    # Note: Adding text via add_blank_page is limited in pypdf for testing text extraction without content stream manipulation.
    # So we'll use a simpler approach: create a dummy PDF with metadata or verify valid PDF handling, 
    # OR better: use a mock if we want to avoid complex PDF generation logic in tests, 
    # BUT better for integration: generate a real minimal PDF.
    
    # Actually, pypdf's PdfWriter doesn't easily let us add text to a page without other libs like reportlab.
    # So we will assume the function takes bytes and verify it handles a valid empty PDF or a mocked one.
    # However, to test *text extraction*, we really need a PDF with text.
    # Let's try to mock the PdfReader in the implementation or use a pre-generated byte string of a simple PDF.
    
    # Minimal PDF with "Hello World" (generated offline or hardcoded base64 is safer)
    pass 

# Simple PDF with "Hello World"
MINIMAL_PDF_BYTES = b'%PDF-1.7\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n3 0 obj\n<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /MediaBox [0 0 200 200] /Contents 5 0 R >>\nendobj\n4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n5 0 obj\n<< /Length 24 >>\nstream\nBT\n/F1 24 Tf\n50 150 Td\n(Hello World) Tj\nET\nendstream\nendobj\nxref\n0 6\n0000000000 65535 f \n0000000009 00000 n \n0000000060 00000 n \n0000000125 00000 n \n0000000251 00000 n \n0000000338 00000 n \ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n412\n%%EOF'

def test_extract_text_from_pdf_valid():
    # Use the hardcoded minimal PDF
    pdf_file = io.BytesIO(MINIMAL_PDF_BYTES)
    text = extract_text_from_pdf(pdf_file)
    assert "Hello World" in text

def test_extract_text_from_pdf_invalid():
    # Test with invalid bytes
    invalid_file = io.BytesIO(b"not a pdf")
    with pytest.raises(Exception): # Expecting some error, likely from pypdf
        extract_text_from_pdf(invalid_file)
